### PR TITLE
[PLOP-2047] Close the noindex tag

### PR DESCRIPTION
**Pull request by dandobrescu**
Trying to downgrade the playground score here, as the noindex meta tag is not properly detected. It's a poor man's attempt as in the PR environments the tag is detected  - for which by the way, if you have any idea why it may see it differently, let me know. I tried to close this tag in case they can't properly parse the html. 

image

### CODE REVIEW

**Comment by dandobrescu** [comment]
@Robvdhout  - this is not  closed either https://github.com/studyportals/CMS/blob/6a3a242177f3a8c97708368e988dae93c6e07534/src/CMS/Page/PageAssets.php#L220

Should I close it also as part of this PR?

**Review by Robvdhout — DISMISSED** [review]

**Comment by dandobrescu** [comment]
> @Robvdhout - this is not closed either
> 
> https://github.com/studyportals/CMS/blob/6a3a242177f3a8c97708368e988dae93c6e07534/src/CMS/Page/PageAssets.php#L220
> 
> Should I close it also as part of this PR?

@Robvdhout  - what about this?

**Comment by Robvdhout** [comment]
> > @Robvdhout - this is not closed either
> > https://github.com/studyportals/CMS/blob/6a3a242177f3a8c97708368e988dae93c6e07534/src/CMS/Page/PageAssets.php#L220
> > 
> > Should I close it also as part of this PR?
> 
> @Robvdhout - what about this?

According to https://html.spec.whatwg.org/multipage/syntax.html#start-tags and https://html.spec.whatwg.org/multipage/syntax.html#void-elements it doesn't do anything, but it won't hurt.

**Comment by dandobrescu** [comment]
> > > @Robvdhout - this is not closed either
> > > https://github.com/studyportals/CMS/blob/6a3a242177f3a8c97708368e988dae93c6e07534/src/CMS/Page/PageAssets.php#L220
> > > 
> > > Should I close it also as part of this PR?
> > 
> > 
> > @Robvdhout - what about this?
> 
> According to https://html.spec.whatwg.org/multipage/syntax.html#start-tags and https://html.spec.whatwg.org/multipage/syntax.html#void-elements it doesn't do anything, but it won't hurt.

From a spec perspective you're right, but it may helps the DOM parsers a lot  -  I think that closing the tag actually fixes the difference in the lighthouse reports

**Review by Robvdhout — APPROVED** [review]

**Review by Robvdhout — APPROVED** [review]

**Pull request merged**
